spring:
  application:
    name: document-api
  datasource:
    # 🌍 OPCIÓN A: PRODUCCIÓN (COOLIFY) - Usa las variables inyectadas por el servidor
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    # 💻 OPCIÓN B: LOCAL - Descomenta estas 3 líneas para pruebas en tu PC
    # url: jdbc:postgresql://51.91.159.188:5433/postgres
    # username: postgres
    # password: yLDXHfdOBe3u9o3q19eyDm9EiXSWTuaI2shMDNkp22QjY6qTCoXD4NvtlFRdHGlG
    
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # 'none' para asegurar el acceso de solo lectura
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: 3000
